org.gradle.jvmargs=-Xmx2G
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true

version=2.0.0-SNAPSHOT
group=xyz.jpenilla
description=Server-side Fabric mod enhancing the console with tab completions, colored log output, command syntax highlighting, command history, and more.
